### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by asdfghjkl403622** [Felk/dolphin#15]
arch linux

[ 46%] Building CXX object Source/Core/Scripting/CMakeFiles/scripting.dir/ScriptingEngine.cpp.o
In file included from /home/samy/dolphin/Source/Core/Scripting/Python/PyScriptingBackend.h:12,
                 from /home/samy/dolphin/Source/Core/Scripting/ScriptingEngine.cpp:10:
/home/samy/dolphin/Source/Core/Core/API/Controller.h: In member function ‘void API::BaseManip<T>::NotifyFrameAdvanced()’:
/home/samy/dolphin/Source/Core/Core/API/Controller.h:37:10: error: ‘erase_if’ is not a member of ‘std’; did you mean ‘enable_if’?
   37 |     std::erase_if(m_overrides, [](const auto& kvp) {
      |          ^~~~~~~~
      |          enable_if
make[2]: *** [Source/Core/Scripting/CMakeFiles/scripting.dir/build.make:76: Source/Core/Scripting/CMakeFiles/scripting.dir/ScriptingEngine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1632: Source/Core/Scripting/CMakeFiles/scripting.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by Felk** [comment]
Thanks for the report!

I believe `std::erase_if` is a C++20 feature. I'll check later if that's true, and if yes de-dust my old ubuntu machine to actually test linux compilation again.

**Comment by asdfghjkl403622** [comment]
Thanks for the quick response!

**Comment by Felk** [comment]
fixed in 26a889a196e43e424f9cc95ce426a92eb58255ee

**Comment by asdfghjkl403622** [comment]
can confirm, is fixed
