### ISSUE TITLE
Regular breakpoints

### ISSUE THREAD

**Issue by TryTwo** [Felk/dolphin#18]
Would it be much trouble to add regular code breakpoints as an event?  MemoryBreakpoints can horribly lag some games (not due to your commits), but regular breakpoints seem to always work fine.

**Comment by Felk** [comment]
Regular breakpoints as in instruction breakpoints? Yes, that sounds like a sensible addition, will keep it in mind, thanks!

**Comment by TryTwo** [comment]
Great. I actually hacked this and register read/write access together in a personal build. It wasn't much work. Would you want me to PR it or does it not particularly matter since they are rather simple additions?

**Comment by Felk** [comment]
That would actually be fantastic!

**Comment by Felk** [comment]
implemented in a34d3575bec3a1b7146d4c2496ca5b965c8aa6a2, thanks again!
