### ISSUE TITLE
add support for pointers

### ISSUE THREAD

**Issue by gitrinitas** [Felk/dolphin#23]
disclaimer: I am not really a programmer so this might be already doable and I'm just dumb lol. I also might use bad terminology, but I tried to be as clear as I could :sweat: 

I want to do stuff with certain game variables, but those variables are not always at the same place in memory. However, you can find these variables using pointers. Unfortunately, as far as I can tell there is no good way to ask dolphin to traverse these pointers atm. 

This is my current solution for finding my speed:
base_vel = memory.read_u32(0x809AFF38)
base_vel = memory.read_u32(base_vel + 0xC)
base_vel = memory.read_u32(base_vel + 0x10)
base_vel = memory.read_u32(base_vel + 0x0)
base_vel = memory.read_u32(base_vel + 0x10)
base_vel = memory.read_u32(base_vel + 0x10)
base_vel = memory.read_f32(base_vel + 0x20)

I'd like to do something like this:
base_vel = memory.read_f32(0x809AFF38, 0xC, 0x10, 0x0, 0x10, 0x10, 0x20)

sorry if this is already doable lol

**Comment by Felk** [comment]
Thanks, that's certainly useful functionality, but I believe this better lives in application code. If it is possible in python, and doesn't have any significant drawbacks when doing it in python, it shouldn't be implemented in the emulator.

Maybe this is a common enough thing that I'll change my mind eventually, but for now you could implement a pointer-chasing variant of the memory read function like this (untested code):
```python
def read_f32_chase(address, *chase_offsets):
    value = memory.read_u32(address)
    for offset in chase_offsets:
        value = memory.read_u32(value + offset)
    return value
```
