### ISSUE TITLE
Build error with new commits

### ISSUE THREAD

**Issue by BLCRAFT210** [Felk/dolphin#27]
I pulled the new commits from the last two days, and now I have a build error on Ubuntu 22.04:
``/usr/bin/ld: ../Scripting/CMakeFiles/scripting.dir/Python/PyScriptingBackend.cpp.o: in function `PyScripting::PyScriptingBackend::PyScriptingBackend(std::filesystem::__cxx11::path, API::GenericEventHub<API::Events::FrameAdvance, API::Events::SetInterrupt, API::Events::ClearInterrupt, API::Events::MemoryBreakpoint, API::Events::CodeBreakpoint>&, API::Gui&, API::GCManip&, API::WiiButtonsManip&, API::WiiIRManip&)':
PyScriptingBackend.cpp:(.text+0x726): undefined reference to `PyInit_registers'
collect2: error: ld returned 1 exit status
make[2]: *** [Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/build.make:2771: Binaries/dolphin-emu] Error 1
make[1]: *** [CMakeFiles/Makefile2:2567: Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/all] Error 2
make: *** [Makefile:156: all] Error 2``

**Comment by Felk** [comment]
Thanks for letting me know! Looks like the new registers module is missing from the CMakeList.

I'll clean a bunch of stuff up once I piled up a bunch of features I wanna put into a new preview release. I will also fix the Linux build then. I'm a bit busy until next week but I'll try to squeeze it in somewhere.

**Comment by Felk** [comment]
fixed in https://github.com/Felk/dolphin/commit/aa2eb68c0d3f91a9d63ba11d7264335b6859f81d
