### ISSUE TITLE
savestate.load_from_slot() causes Dolphin to hang from within a loop

### ISSUE THREAD

**Issue by benjaminjmiddleton** [Felk/dolphin#35]
Here's a simplified snippet from my script for Mario Kart Wii:
```
savestate.load_from_slot(1) # works fine

while True:
    (width, height, data) = await event.framedrawn()

    if frame_counter > 460:
        frame_counter = 0
        savestate.load_from_slot(1) # causes Dolphin to hang
        continue
```

For some reason, the second call to load_from_slot causes Dolphin to hang. It works fine the first time (out of the loop).

Let me know if I can provide any additional detail.

**Comment by BLCRAFT210** [comment]
Same issue as #32. You can see a few iffy workarounds to this problem in that thread.
