### ISSUE TITLE
Emulator freezes when loading saveslot from created thread

### ISSUE THREAD

**Issue by Whitelisted1** [Felk/dolphin#49]
Hey there, after using the latest scripting preview ([scripting-preview-3](https://github.com/Felk/dolphin/releases/tag/scripting-preview3)), I've noticed that my emulator occasionally freezes when loading a saveslot from a thread created using Python's threading module.

I am using this code to test after noticing the issue in another project:
```python
import dolphin
import threading
import time


def main():
    while True:
        time.sleep(0.25)
        print("Loading from slot 1 ...")
        dolphin.savestate.load_from_slot(1)
        print("Loaded from slot 1")


threading.Thread(target=main).start()
```

After running this code for only about a minute, the emulator freezes, shown in the video below

https://github.com/Felk/dolphin/assets/77711834/aca0b27f-2ad8-4278-9656-9b7270ce78b6

I have not tested to see if this issue still occurs in past versions of this project. I've also noticed that this can happen when reading the memory with `dolphin.memory`.

**Comment by Whitelisted1** [comment]
This issue was not occurring in the main thread, though, after being tested with this code for a few minutes:
```python
import dolphin

i = 0
while True:
    i += 1
    await dolphin.event.frameadvance()

    if i % 30 == 0:
        print("Loading from slot 1 ...")
        dolphin.savestate.load_from_slot(1)
        print("Loaded from slot 1")
```

**Comment by VIPTankz** [comment]
I have also noticed this issue; currently I've just been restarting the program.

**Comment by mkzeender** [comment]
I mean, just in general, arbitrary memory access is not threadsafe.

Since the main thread is asynchronous, you can define a coroutine, and then in your other thread, use asyncio.call_soon_threadsafe() call it.

**Comment by Whitelisted1** [comment]
> I mean, just in general, arbitrary memory access is not threadsafe.
> 
> Since the main thread is asynchronous, you can define a coroutine, and then in your other thread, use asyncio.call_soon_threadsafe() call it.

Thanks for the info, sorry that I missed that
