### ISSUE TITLE
Gamecube controller  script not working

### ISSUE THREAD

**Issue by programer786** [Felk/dolphin#7]
Hello,
I found your post on stackoverflow: https://stackoverflow.com/questions/32064844/python-interact-with-dolphin-emulator
I tried to test that code, I just installed this release: https://github.com/Felk/dolphin/releases
Then I made a python script which I put on my desktop called "new.py" and put in it the code that you posted on stackoverflow.
I've opened dolphin from your release, pressed on add new script and selected the "new.py" on my desktop.
But nothing's happening, the game plays normally like in normal dolphin, the A button isn't pressed by the python script but I can press it normally on my keyboard.

**Comment by Felk** [comment]
Hello, thanks for reaching out. Can you enable logging as described in the readme and post the output? There may be some errors

**Comment by Felk** [comment]
I also noticed that I renamed `get_gc` and `set_gc` to `get_gc_buttons` and `set_gc_buttons` since then. That may already fix the issue

**Comment by programer786** [comment]
Hello,
Thanks for the quick response. When I try to run the example code from the readme then I do get the "Hello Dolphin!" at each frame of the log
But nothing happens with the other code.
I tried to add some print functions to it but I guess the data type of buttons isn't printable since there's no output. Here's the code:
`from dolphin import controller, event

while True:
    await event.frameadvance()
    buttons = controller.get_gc_buttons()
    print(buttons)
    buttons["A"] = True
    print(buttons)
    controller.set_gc_buttons(buttons)
    await event.frameadvance()
    # do nothing every other frame
`
I've tried to change the verbosity type in the log configuration but without success either.

**Comment by Felk** [comment]
Yeah, I'm sorry, the example was still wrong. I managed to get this to work:
```python
from dolphin import controller, event

while True:
    await event.frameadvance()
    buttons = controller.get_gc_buttons(0)
    buttons["A"] = True
    controller.set_gc_buttons(0, buttons)
    await event.frameadvance()
    # do nothing every other frame
```
note that both `get_gc_buttons` and `set_gc_buttons` take the controller number as first parameter. For other functions you can find the functions' signatures in the [dolphin-stubs](https://github.com/Felk/dolphin/tree/master/dolphin-stubs) directory in the repository.

This is the log configuration I used: 
![image](https://user-images.githubusercontent.com/1996138/110978785-18bdeb00-8364-11eb-9b86-eac5964b49e7.png)

and before I added the zeroes as first parameters I got these outputs in the "Log"-Tab:
```
48:34:118 Scripting\Python\Modules\doliomodule.cpp:36 E[Scripting]: Script stderr: Traceback (most recent call last):
48:34:118 Scripting\Python\Modules\doliomodule.cpp:36 E[Scripting]: Script stderr:   File "C:/Users/felk/Desktop/test.py", line 5, in <module>
48:34:118 Scripting\Python\Modules\doliomodule.cpp:36 E[Scripting]: Script stderr:     buttons = controller.get_gc_buttons()
48:34:118 Scripting\Python\Modules\doliomodule.cpp:36 E[Scripting]: Script stderr: TypeError: function takes exactly 1 argument (0 given)
```

Please make sure you are able to see these errors too. And let me know if the code snippet above is working for you

**Comment by programer786** [comment]
Hello,
Thanks it's working now! This is very impressive, thanks for all the work.
I thought I had tried all the verbose types yesterday but I didn't get any output, but it worked today. I'm getting the same output as you if I remove the zeros.
I've tried to find out why it wasn't giving me the warning yesterday and apparently I need to reload the script to get the error to show. If I try the normal "notice" verbose and start the game and then try the warning verbose later without reloading the script it won't show the error even if I reload the game. Maybe this is something normal and not a bug. If yes, I think that it would be good to add it to the readme.

**Comment by Felk** [comment]
> Thanks it's working now!

That's good to hear.

> I've tried to find out why it wasn't giving me the warning yesterday and apparently I need to reload the script to get the error to show.

Yes. Changing the error level does not work retroactively. Reloading the script causes the error to be printed again however.

> If I try the normal "notice" verbose [...] it won't show the error. Maybe this is something normal.

Yes, that is indeed normal, since NOTICE is a less verbose log level than ERROR. I think it's a good idea to mention, since I suppose a lot of people aren't familiar with log levels.
